ALTER DATABASE [Ventes] ADD FILE ( NAME = N'DATA_F1bis', FILENAME = N'D:\Disques\DATA_F1bis.ndf' , SIZE = 8192KB , FILEGROWTH = 65536KB ) TO FILEGROUP [DATA]

GO
DBCC SHRINKFILE (N'DATA_F1', EMPTYFILE);


ALTER DATABASE [Ventes]  REMOVE FILE [DATA_F1]
GO